### ISSUE TITLE
Are these issues being maintained anymore?

### ISSUE THREAD

**Issue by estiens** [hubot-scripts/packages#137]
Seems it has been a long time since any scripts were forked to this organization.

**Comment by technicalpickles** [comment]
https://github.com/hubot-scripts/packages/issues/60 has all the background. Basically, forking to this organization, adding teams, etc is tedious & time consuming.

Part of the original point was having a place to find scripts, but it turns out that SEO for forks isn't great (the original comes up first). I'd prefer to move towards documenting how to find scripts in a different way, ie https://github.com/github/hubot/issues/901

**Comment by bkeepers** [comment]
I'm going to work on pushing #60 forward and close this. Let me know if you have any questions.

**Comment by therealklanni** [comment]
:+1: @bkeepers
